model:
  node1: 1
  node2: 2

optimizer:
  learning_rate: 0.001
  momentum: 0.9

train:
  epoch: 5

mlflow:
  # tracking_uri: http://localhost:5001
  experiment_name: "my_experiment"
  run_name: "my_run"

# この行は、MLflowのトラッキングURI（Uniform Resource Identifier）を設定しています。
# MLflowは、実験結果を保存し、トラッキングするためのデータベースやストレージバックエンドと連携する必要があります。
# このURIは、どのデータベースやストレージバックエンドを使用するかを指定します。
# URIは通常、データベースの接続文字列やローカルファイルパスに関連します
# MLflowでは、実験ごとに実行されたトレーニングや評価などの実験結果を区別し、管理することができます。各実験は一意の名前（experiment_name）で識別されます。
